defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  host: localhost
  port: 3306

development:
  <<: *defaults
  database: budget-development

test:
  <<: *defaults
  database: budget-test
